server:
  port: 8091

management:
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: false
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "https://budget-tracker-4de96.web.app"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allow-credentials: true

      routes:
        - id: budgetapp
          uri: "http://172.31.17.255:8082"
          predicates:
            - Path=/budget/**, /category-budget/**
        - id: expenseapp
          uri: "http://172.31.17.255:8083"
          predicates:
            - Path=/expense/**

  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    hikari:
      schema: budget_tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    root: trace

firebaseWebKey: ${FIREBASE_WEB_KEY}